// Nguyen Thien Nhan (Revolution)
#include <bits/stdc++.h>
#define ll long long
using namespace std;
const ll MAXN = 1e6 + 5;

bool visited[MAXN];
queue q[MAXN];
vector adj[MAXN];
ll a[MAXN][MAXN];

ll m, n, u, v;

void input() {
	
	cin >> m >> n >> u >> v;
	
	for ( ll i = 1; i <= m; i++ ) 
		for ( ll j = 1; j <= n; j++ ) cin >> a[i][j];
		
	for ( ll i = 1; i <= m; i++ ) 
		for ( ll j = 1; j <= n; j++ ) {
			adj[]
		}
		
	memset ( visited, false, sizeof ( visited ) );
}


void dfs( ) {
	
	for ( ll i = )
}


int main() {
	ios_base::sync_with_stdio(false); cin.tie(NULL); cout.tie(NULL);
   	//freopen (".INP","r", stdin);
	//freopen (".OUT","w", stdout);

	return 0;
}


